name: Audit Backend

on:
  schedule:
    - cron: "4 2 * * 0"
  push:
    paths:
      - "src-tauri/Cargo.lock"

jobs:
  audit_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
      - run: npm run audit:backend
