name: Format Backend

on:
  push:
    paths:
      - "src-tauri/**"

jobs:
  format_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: npm ci
      - run: npm run format:backend
