name: Format Backend

on:
  push:
    paths:
      # TODO remove this
      - ".github/workflows/format-backend.yml"
      - "src-tauri/**"

jobs:
  format_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libleptonica-dev
          libtesseract-dev
      - run: npm ci
      - run: npm run build
      - run: npm run tauri icon
      - run: npm run format:backend
