name: Lint Backend

on:
  push:
    paths:
      # TODO remove this
      - ".github/workflows/lint-backend.yml"
      - "src-tauri/**"

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: npm ci
      - run: npm run lint:backend
