name: Lint Backend

on:
  push:
    paths:
      - "src-tauri/**"
      - "package.json"
      - ".github/workflows/lint-backend.yml"

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libleptonica-dev
          libtesseract-dev
      - run: npm ci
      - run: npm run build
      - run: npm run tauri icon
      - uses: actions/cache@v3
        with:
          key: rust-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('src-tauri/**', 'app-icon.png') }}-lint
          restore-keys: |
            rust-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('src-tauri/**', 'app-icon.png') }}-
            rust-${{ steps.toolchain.outputs.rustc_hash }}-
            rust-
          path: |
            src-tauri/target
            ~/.cargo
      - run: npm run lint:backend
